# Travis's native R Image (http://docs.travis-ci.com/user/languages/r/)
language: r
sudo: required
cache: packages
warnings_are_errors: true
apt_packages:
 - iodbc
 - unixodbc
 - unixodbc-dev
 - r-cran-rodbc
r_github_packages:
  - jimhester/covr
  - Tazinho/snakecase
  - decisionpatterns/lettercase
after_success:
  - Rscript -e 'library(covr);coveralls()'
